# Generated by Django 5.2.1 on 2025-05-21 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('ACC', 'ACCION'), ('AVE', 'AVENTURA'), ('RPG', 'RPG'), ('EST', 'ESTRATEGIA'), ('DEP', 'DEPORTES'), ('SAN', 'SANDBOX')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clave_juego', models.CharField(max_length=255)),
                ('terminos_y_condiciones', models.BooleanField(default=True)),
                ('en_venta', models.BooleanField(default=True)),
                ('vendida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('acepto_terminos', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('u', 'Usuario'), ('v', 'Vendedor')], default='u', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prinkeyhub.clave')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prinkeyhub.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='clave',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prinkeyhub.usuario'),
        ),
    ]
