# Generated by Django 5.2.1 on 2025-05-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prinkeyhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clave',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img_juegos/'),
        ),
        migrations.AddField(
            model_name='clave',
            name='plataforma',
            field=models.CharField(choices=[('PC', 'PC'), ('XBOX', 'XBOX'), ('PS5', 'PS5')], default='PC', max_length=50),
        ),
    ]
