# Generated by Django 5.2.1 on 2025-05-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prinkeyhub', '0002_clave_imagen_clave_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clave',
            name='imagen',
            field=models.ImageField(blank=True, default='default/defaul.jpeg', null=True, upload_to='img_juegos/'),
        ),
    ]
